import { svLocale } from "./Localization/sv-SV";

export const BASE_URL = "http://www.metrojobb.se";
export const SEARCH_AD_URL = "/ws/search/searchjobad?";

export const jobbKategorier = [
    { value: "1", label: "Administration" },,
    { value: "2", label: "Bygg & Anläggning" },,
    { value: "3", label: "Data / IT" },
    { value: "4", label: "Drift & Underhåll" },
    { value: "5", label: "Ekonomi & Finans" },
    { value: "6", label: "Forskning / R&D / Vetenskap" },
    { value: "7", label: "Försäljning / Affärsutveckling" },
    { value: "8", label: "Hotell / Restaurang / Turism" },
    { value: "9", label: "HR & Personal" },
    { value: "10", label: "Juridik" },
    { value: "11", label: "Kreativitet / Design" },
    { value: "12", label: "Kundsupport & Service" },
    { value: "13", label: "Säkerhet & Kontroll" },
    { value: "14", label: "Ledning / Chefer" },
    { value: "15", label: "Logistik / Transport" },
    { value: "16", label: "Marknadsföring / Produkt" },
    { value: "17", label: "Projektledning" },
    { value: "18", label: "Trainee" },
    { value: "19", label: "Sjukvård & Hälsa" },
    { value: "20", label: "Skribenter / publishing" },
    { value: "21", label: "Teknik" },
    { value: "22", label: "Industri / Produktion" },
    { value: "23", label: "Lärare / Utbildning" },
    { value: "24", label: "Övrigt" },
    { value: "25", label: "Artister / Skådespelare" },
    { value: "26", label: "Franchisetagare" }
];

export function specifikJobbKategori(numberInput: any) {
    switch(numberInput) {
        case "1":
          return [
            { value: "100", label: "Administration Import / Export" },
            { value: "101", label: "Arkivarie / Registrator" },
            { value: "102", label: "Assistent" },
            { value: "103", label: "VD-assistent / chefssekreterare (chefsassistent)" },
            { value: "104", label: "Registrator" },
            { value: "105", label: "Fastighetsförvaltare" },
            { value: "106", label: "Administratör" },
            { value: "107", label: "Receptionist / Telefonist" },
            { value: "108", label: "Sekreterare" },
            { value: "109", label: "Övrigt: Administration" }
          ];
        case "2":
          return [
            { value: "200", label: "Arbetsledare / Byggprojektledare / Platschef" },
            { value: "201", label: "CAD / CAM" },
            { value: "202", label: "Elektriker" },
            { value: "203", label: "Fasad" },
            { value: "204", label: "Lantmätare / Samhällsplanerare" },
            { value: "205", label: "Maskinarbete" },
            { value: "206", label: "Metallarbete / Svetsare" },
            { value: "207", label: "Armerare / Betongarbetare" },
            { value: "208", label: "Målare / Golvläggare" },
            { value: "209", label: "Takläggare" },
            { value: "210", label: "Träarbetare / Snickare" },
            { value: "211", label: "VVS-montör" },
            { value: "212", label: "Värme / Ventilation" },
            { value: "213", label: "Övrigt: Bygg / Anläggning / Infrastruktur" },
            { value: "214", label: "Byggnad / konstruktion" }
          ]
        case "3":
          return [
            { value: "300", label: "IT-konsult" },
            { value: "301", label: "IT-säkerhet" },
            { value: "302", label: "Nätverksspecialist / Serverspecialist" },
            { value: "303", label: "Systemanalytiker / Testare" },
            { value: "304", label: "Systemarkitekt" },
            { value: "305", label: "Utvecklare / Programmerare" },
            { value: "306", label: "Teknisk projektledare" },
            { value: "307", label: "IT-support" },
            { value: "309", label: "Warehousing / Databasadministration" },
            { value: "310", label: "Webbdesigner / Grafisk designer" },
            { value: "311", label: "Webbutvecklare" },
            { value: "312", label: "Övrigt: Data / IT" }
          ];
        case "4":
          return [
            { value: "400", label: "Elektriker" },
            { value: "401", label: "Fastighetsskötare / HVAC" },
            { value: "402", label: "Mekaniker / Fordon" },
            { value: "403", label: "IT Drift / Underhåll" },
            { value: "404", label: "Karossreparatör / Lackerare" },
            { value: "405", label: "Lokalvårdare / Bostad" },
            { value: "406", label: "Lås / Säkerhet" },
            { value: "407", label: "Maskintekniker" },
            { value: "408", label: "Oljeriggsarbetare" },
            { value: "409", label: "Städare / Hushållsskötsel" },
            { value: "410", label: "Trädgårdsarbetare" },
            { value: "411", label: "Vaktmästare / Lokalvård" },
            { value: "412", label: "VVS-montör" },
            { value: "413", label: "Värme / Ventilation" },
            { value: "414", label: "Övrigt: Drift & Underhåll" }
          ];
        case "5":
          return [
            { value: "500", label: "Banktjänster privatmarknad" },
            { value: "501", label: "Beskattning" },
            { value: "502", label: "Börsmäklare" },
            { value: "503", label: "Controller / Rapportering" },
            { value: "504", label: "Corporate Finance" },
            { value: "505", label: "Fastigheter leasing" },
            { value: "506", label: "Fastighetsvärdering" },
            { value: "507", label: "Financial controller" },
            { value: "508", label: "Fondredovisning" },
            { value: "509", label: "Försäkringar" },
            { value: "510", label: "Inkasso" },
            { value: "511", label: "Inköpare / Investeringar" },
            { value: "512", label: "Kredithandläggare / Lånehandläggare" },
            { value: "513", label: "Placeringsrådgivning / Förvaltning" },
            { value: "514", label: "Planering / Rådgivning" },
            { value: "515", label: "Redovisningsekonom" },
            { value: "516", label: "Reskontra" },
            { value: "517", label: "Revisor" },
            { value: "518", label: "Riskanalys" },
            { value: "519", label: "Skatterådgivning" },
            { value: "520", label: "Värdepapper / Analys" },
            { value: "521", label: "Övrigt: Ekonomi & Finans" },
            { value: "522", label: "Ekonomiassistent" }
          ];
        case "6":
          return [
            { value: "600", label: "Farmakologi" },
            { value: "601", label: "Forskning Agronomi / Miljö" },
            { value: "602", label: "Forskning Biologi / Kemi" },
            { value: "603", label: "Forskning Fysik" },
            { value: "604", label: "Forskning Ledning" },
            { value: "605", label: "Kliniska studier" },
            { value: "606", label: "Matematik / Statistik" },
            { value: "607", label: "Övrigt: Forskning / R&D / Vetenskap" }  
          ];
        case "7":
          return [
            { value: "700", label: "Säljare / Account manager" },
            { value: "701", label: "Affärsutvecklare / Säljchef" },
            { value: "702", label: "Butiksbiträde" },
            { value: "703", label: "E-handel" },
            { value: "704", label: "Fastighetsmäklare" },
            { value: "705", label: "Fältsäljare" },
            { value: "706", label: "Försäkringsmäklare" },
            { value: "707", label: "Grossist" },
            { value: "708", label: "Internationell försäljning" },
            { value: "709", label: "Mediasäljare" },
            { value: "710", label: "Reseförsäljning" },
            { value: "711", label: "Säljsupport" },
            { value: "712", label: "Teknisk säljare" },
            { value: "713", label: "Telefonförsäljare" },
            { value: "714", label: "Värdepapper / Analys" },
            { value: "715", label: "Övrigt: Försäljning / Affärsutveckling" }  
          ];
        case "8":
          return [
            { value: "800", label: "Dryckservering / Bar" },
            { value: "801", label: "Gästservice / Portvakt" },
            { value: "802", label: "Kök / Matlagning" },
            { value: "803", label: "Ledning Hotell / Konferens" },
            { value: "804", label: "Receptionist" },
            { value: "805", label: "Restaurangchef" },
            { value: "806", label: "Servering" },
            { value: "807", label: "Souschef" },
            { value: "808", label: "Övrigt: Hotell / Restaurang / Turism" }
          ];
        case "9":
          return [
            { value: "900", label: "Headhunting" },
            { value: "901", label: "HR Kompetensutveckling" },
            { value: "902", label: "HR / Löneadministratör" },
            { value: "903", label: "HR-assistent" },
            { value: "904", label: "HR-konsult" },
            { value: "905", label: "Karriärcoaching" },
            { value: "906", label: "Rekryterare" },
            { value: "907", label: "Övrigt: HR & Personal" }  
          ];
        case "10":
          return [
            { value: "1000", label:  "Advokat" },   
            { value: "1001", label:  "Affärsjuridik" },   
            { value: "1002", label:  "Arbetsrättsjuridik" },   
            { value: "1003", label:  "Fastighetsjurist" },   
            { value: "1004", label:  "Immaterialrätt" },   
            { value: "1005", label:  "Reglerande juridik" },   
            { value: "1006", label:  "Skatterätt" },   
            { value: "1007", label:  "Övrigt: Juridik" }
          ];
        case "11":
          return [
            { value: "1100", label:  "Arkitektur / Inredning" },   
            { value: "1101", label:  "Copywriter" },   
            { value: "1102", label:  "Dataanimation & Multimedia" },   
            { value: "1103", label:  "Film / Fotografering" },   
            { value: "1104", label:  "Illustration / Originalarbete" },   
            { value: "1105", label:  "Industridesign" },
            { value: "1106", label:  "Kreativ ledning" },   
            { value: "1107", label:  "Modedesign" },
            { value: "1108", label:  "Webb / grafisk design" },
            { value: "1109", label:  "Övrigt: Kreativitet / Design" }
          ];
        case "12":
          return [
            { value: "1200", label:  "Bankkassör" },
            { value: "1201", label:  "Butiksarbete" },
            { value: "1202", label:  "Kundtjänstmedarbetare" },
            { value: "1203", label:  "Kabinpersonal" },
            { value: "1204", label:  "Frisör / Stylist" },
            { value: "1206", label:  "Ordermottagare / bokare" },
            { value: "1207", label:  "Servicepersonal flygplats" },
            { value: "1208", label:  "Säljsupport / Kundutbildning" },
            { value: "1209", label:  "Teknisk support" },
            { value: "1210", label:  "Vaktmästare" },
            { value: "1211", label:  "Övrigt: Kundsupport & Service" }  
          ];
        case "13":
          return [
            { value: "1300", label:  "Bedrägeriutredning" },
            { value: "1301", label:  "Byggnadsinpektion" },
            { value: "1302", label:  "Farligt material städning" },
            { value: "1303", label:  "Flygplan / skeppsinspektion" },
            { value: "1304", label:  "Fordonsbesiktning" },
            { value: "1305", label:  "ISO certifiering" },
            { value: "1306", label:  "Kvalitetssäkring Mjukvara" },
            { value: "1307", label:  "Kvalitetssäkring Produktion" },
            { value: "1308", label:  "Livsmedelsinspektion" },
            { value: "1309", label:  "Miljöskyddsinspektion" },
            { value: "1310", label:  "Six Sigma / Black Belt / TQM" },
            { value: "1311", label:  "Skyddsombud" },
            { value: "1312", label:  "Brandman" },
            { value: "1313", label:  "Butikssäkerhet" },
            { value: "1314", label:  "Gränsövervakning" },
            { value: "1315", label:  "Kriminalvård" },
            { value: "1316", label:  "Militär / Försvar" },
            { value: "1317", label:  "Polis" },
            { value: "1318", label:  "Säkerhetskontrollant flygplats" },
            { value: "1319", label:  "Säkerhetstransporter" },
            { value: "1320", label:  "Tull / Immigration" },
            { value: "1321", label:  "Väktare" },
            { value: "1322", label:  "Övrigt: Säkerhet & Kontroll" }
          ];
        case "14":
          return [
            { value: "1400", label:  "Avdelningschef Butik" },
            { value: "1401", label:  "Butikschef" },
            { value: "1402", label:  "Enhetschef / Affärsområdeschef" },
            { value: "1403", label:  "Ekonomichef / Ekonomidirektör" },
            { value: "1404", label:  "Fusioner & förvärv" },
            { value: "1405", label:  "Företagsanalys / research" },
            { value: "1406", label:  "Gruppchef / Teamleader" },
            { value: "1407", label:  "Kommunledning" },
            { value: "1408", label:  "Konsultchef / Verksamhetskonsult" },
            { value: "1409", label:  "Omsorgsadministration" },
            { value: "1410", label:  "Rektor" },
            { value: "1411", label:  "Restaurangchef" },
            { value: "1412", label:  "Sjukhusledning" },
            { value: "1413", label: "Finanschef / Finansdirektör" },
            { value: "1414", label: "VD / CEO / Företagsledning" },
            { value: "1415", label: "Övrigt Ledning" },
            { value: "1416", label: "Försäljningschef / Försäljningsdirektör" },
            { value: "1417", label: "Marknadschef / Marknadsdirektör" },
            { value: "1418", label: "HR-chef / Personalchef / Hr-direktör / Personaldirektör" },
            { value: "1419", label: "IT-chef / IT-direktör" },
            { value: "1420", label: "Affärsutvecklingschef / Affärsutvecklingsdirektör" }  
          ];
        case "15":
          return [
            { value: "1500", label: "Administration Import / Export" },
            { value: "1501", label: "Brevbärare" },
            { value: "1502", label: "Chaufför / Lokförare" },
            { value: "1503", label: "Expedition" },
            { value: "1504", label: "Hantering Last / Bagage" },
            { value: "1505", label: "Inköpare / Supply planner" },
            { value: "1506", label: "Kranarbete" },
            { value: "1507", label: "Lager Planering / Ledning" },
            { value: "1508", label: "Lager Terminal / Truck" },
            { value: "1509", label: "Lastbilschaufför" },
            { value: "1510", label: "Leverans / Distribution" },
            { value: "1511", label: "Logistik Material / Produktion" },
            { value: "1512", label: "Logistik / Kontroll" },
            { value: "1513", label: "Pilot / Flygledning" },
            { value: "1514", label: "Sophantering / Återvinning" },
            { value: "1515", label: "Speditör" },
            { value: "1516", label: "Säkerhetstransporter" },
            { value: "1517", label: "Övrigt: Logistik / Transport" }
          ];
        case "16":
          return [
            { value: "1600", label: "Brand manager" },
            { value: "1601", label: "Copywriter" },
            { value: "1602", label: "CRM" },
            { value: "1603", label: "Eventmarknadsföring" },
            { value: "1604", label: "Marknadsanalytiker" },
            { value: "1605", label: "Mediarådgivning" },
            { value: "1606", label: "Informatör / PR" },
            { value: "1607", label: "PPC / SEM / SEO specialist" },
            { value: "1608", label: "Produktutveckling" },
            { value: "1609", label: "Skyltning / Dekoration" },
            { value: "1611", label: "Webbkommunikatör / Webbredaktör" },
            { value: "1612", label: "Övrigt: Marknad / Produkt" },
            { value: "1613", label: "Marknadsprojektledare" },
            { value: "1614", label: "Marknadsundersökare/intervjuare" }
          ];
        case "17":
          return [
            { value: "1700", label: "Bostadsplanerare" },
            { value: "1701", label: "Programledning" },
            { value: "1702", label: "Projektledare" },
            { value: "1703", label: "Projektledning Event / Mässor" },
            { value: "1704", label: "Teknisk projektledning" },
            { value: "1705", label: "Övrigt: Projektledning" }
          ];
        case "18":
          return [
            { value: "1800", label: "Administration" },
            { value: "1801", label: "Bygg & Anläggning" },
            { value: "1802", label: "Data / IT" },
            { value: "1803", label: "Drift & Underhåll" },
            { value: "1804", label: "Ekonomi & Finans" },
            { value: "1805", label: "Forskning / R&D / Vetenskap" },
            { value: "1806", label: "Försäljning / Affärsutveckling" },
            { value: "1807", label: "Hotell / Restaurang / Turism" },
            { value: "1808", label: "HR & Personal" },
            { value: "1809", label: "Juridik" },
            { value: "1810", label: "Kreativitet / Design" },
            { value: "1811", label: "Kundsupport & Service" },
            { value: "1812", label: "Säkerhet & Kontroll" },
            { value: "1813", label: "Ledning / Chefer" },
            { value: "1814", label: "Logistik / Transport" },
            { value: "1815", label: "Marknadsföring / Produkt" },
            { value: "1816", label: "Projektledare" },
            { value: "1818", label: "Sjukvård & Hälsa" },
            { value: "1819", label: "Skribenter / publishing" },
            { value: "1820", label: "Teknik" },
            { value: "1821", label: "Industri / Produktion" },
            { value: "1822", label: "Lärare / Utbildning" },
            { value: "1823", label: "Övrigt: Trainee" }  
          ];
        case "19":
         return [
            { value: "1900", label: "Akutsjukvård" },
            { value: "1901", label: "Apotekare / Farmaceutisk rådgivare" },
            { value: "1902", label: "Hemvård / Personlig assistent" },
            { value: "1903", label: "Dietist" },
            { value: "1904", label: "Laboratoriearbete" },
            { value: "1905", label: "Läkare" },
            { value: "1906", label: "Läkarsekreterare" },
            { value: "1907", label: "Psykolog" },
            { value: "1908", label: "Naprapat / Massör" },
            { value: "1909", label: "Omsorgsadministration" },
            { value: "1910", label: "Optik" },
            { value: "1911", label: "Röntgen" },
            { value: "1912", label: "Sjukgymnast" },
            { value: "1913", label: "Sjuksköterska" },
            { value: "1914", label: "Biståndsbedömare / Biståndshandläggare" },
            { value: "1915", label: "Tandläkare" },
            { value: "1916", label: "Veterinär / Djurvård" },
            { value: "1917", label: "Övrigt: Sjukvård / Hälsa" },
            { value: "1918", label: "Apotekschef" },
            { value: "1919", label: "Socionom / Socialsekreterare" },
            { value: "1920", label: "Terapeut" },
            { value: "1921", label: "Undersköterska" },
            { value: "1922", label: "Omsorg" }
         ];
        case "20":
          return [
            { value: "2000", label: "Journalistik" },
            { value: "2001", label: "Korrektur / redigering" },
            { value: "2002", label: "Manuskriptförfattare" },
            { value: "2003", label: "Teknisk dokumentatör" },
            { value: "2004", label: "Översättare" },
            { value: "2005", label: "Övrigt: Skribenter / publishing" }
          ];
        case "21":
          return [
            { value: "2100", label: "Biomedicinsk analytiker" },
            { value: "2102", label: "CAD / CAM" },
            { value: "2103", label: "El / Elektronik" },
            { value: "2104", label: "Elkraftsingenjör" },
            { value: "2105", label: "Flyg / luftfart" },
            { value: "2106", label: "Kemist" },
            { value: "2107", label: "Marinteknik" },
            { value: "2108", label: "Mekaniker" },
            { value: "2109", label: "Miljö / Geo" },
            { value: "2110", label: "Produktionstekniker" },
            { value: "2111", label: "Radio / trådlöst / telekom" },
            { value: "2112", label: "System- / Processteknik" },
            { value: "2113", label: "Övrigt: Teknik" },
            { value: "2114", label: "Laboratorieingenjör" }
          ];
        case "22":
          return [
            { value: "2200", label: "Audio / Video Sändning & Produktion" },
            { value: "2201", label: "Fabriksledning" },
            { value: "2202", label: "Fiske" },
            { value: "2203", label: "Formgjutning" },
            { value: "2204", label: "Lantbrukare / Växthusodlare" },
            { value: "2205", label: "Livsmedelstillverkning" },
            { value: "2206", label: "Maskinarbete" },
            { value: "2208", label: "Montör" },
            { value: "2209", label: "Postarbete" },
            { value: "2210", label: "Produktionsledare" },
            { value: "2211", label: "Renhållning" },
            { value: "2212", label: "Skrädderiarbete" },
            { value: "2213", label: "Sophantering / Återvinning" },
            { value: "2214", label: "Svarvare / CNC-operatör" },
            { value: "2215", label: "Telekommunikation" },
            { value: "2216", label: "Tryck / Grafisk produktion" },
            { value: "2217", label: "Övrigt: Tillverkning / Produktion" }
          ];
        case "23":
          return [
            { value: "2300", label: "Förskollärare / Barnskötare" },
            { value: "2301", label: "Grundskollärare 1-7 / Fritidspedagog" },
            { value: "2302", label: "Grundskollärare 4-9" },
            { value: "2303", label: "Gymnasielärare" },
            { value: "2304", label: "HR Kompetensutveckling" },
            { value: "2305", label: "Idrottslärare" },
            { value: "2306", label: "Lärarassistans" },
            { value: "2307", label: "Skoladministration / Ledning" },
            { value: "2308", label: "Specialpedagog / Speciallärare" },
            { value: "2309", label: "Säljsupport / Kundutbildning" },
            { value: "2310", label: "Universitetsadjunkt" },
            { value: "2311", label: "Utbildare - IT" },
            { value: "2312", label: "Studie- och yrkesvägledare" },
            { value: "2313", label: "Övrigt: Utbildning" },
            { value: "2314", label: "Universitetslektor" }
          ];
        case "24":
          return [
            { value: "2400", label: "Arbeta hemifrån" },
            { value: "2401", label: "Rekryteringsmässor" },
            { value: "2402", label: "Övrigt" }
          ];
        case "25":
          return [
            { value: "2501", label: "Modell / Mannekäng" },
            { value: "2502", label: "Skådespelare" },
            { value: "2503", label: "Showartist / Dansare" },
            { value: "2504", label: "Sång / Musik" },
            { value: "2505", label: "Assistent / Funktionär" },
            { value: "2506", label: "Publik / Deltagare" },
            { value: "2507", label: "Statist" },
            { value: "2519", label: "Övrigt: Artister / Underhållninlabel" }
          ];
        case "26":
          return [
            { value: "26", label: "Franchisetagare" },
          ];
        default:
        return [
            { value: "", label: svLocale.valjKategori },
        ]

      }
}


export const lanKoder = [
    { value: "01", label: "Stockholms län" },,
    { value: "03", label: "Uppsala län" },,
    { value: "04", label: "Södermanlands län" },,
    { value: "05", label: "Östergötlands län" },,
    { value: "06", label: "Jönköpings län" },,
    { value: "07", label: "Kronobergs län" },,
    { value: "08", label: "Kalmar län" },,
    { value: "09", label: "Gotlands län" },,
    { value: "10", label: "Blekinge län" },,
    { value: "12", label: "Skåne län" },,
    { value: "13", label: "Halland län" },,
    { value: "14", label: "Västra Götalands län" },,
    { value: "17", label: "Värmlands län" },,
    { value: "18", label: "Örebro län" },,
    { value: "19", label: "Västmanlands län" },,
    { value: "20", label: "Dalarnas län" },,
    { value: "21", label: "Gävleborgs län" },,
    { value: "22", label: "Västernorrlands län" },,
    { value: "23", label: "Jämtlands län" },,
    { value: "24", label: " Västerbottens län" },,
    { value: "25", label: "Norrbottens län" },
];

export const kommunKoder = [
    { value: "0114", label: "Upplands Väsby" },
    { value: "0115", label: "Vallentuna" },
    { value: "0117", label: "Österåker" },
    { value: "0120", label: "Värmdö" },
    { value: "0123", label: "Järfälla" },
    { value: "0125", label: "Ekerö" },
    { value: "0126", label: "Huddinge" },
    { value: "0127", label: "Botkyrka" },
    { value: "0128", label: "Salem" },
    { value: "0136", label: "Haninge" },
    { value: "0138", label: "Tyresö" },
    { value: "0139", label: "Upplands-Bro" },
    { value: "0140", label: "Nykvarn" },
    { value: "0160", label: "Täby" },
    { value: "0162", label: "Danderyd" },
    { value: "0163", label: "Sollentuna" },
    { value: "0180", label: "Stockholm" },
    { value: "0181", label: "Södertälje" },
    { value: "0182", label: "Nacka" },
    { value: "0183", label: "Sundbyberg" },
    { value: "0184", label: "Solna" },
    { value: "0186", label: "Lidingö" },
    { value: "0187", label: "Vaxholm" },
    { value: "0188", label: "Norrtälje" },
    { value: "0191", label: "Sigtuna" },
    { value: "0192", label: "Nynäshamn" },
    { value: "0305", label: "Håbo" },
    { value: "0319", label: "Älvkarleby" },
    { value: "0330", label: "Knivsta" },
    { value: "0331", label: "Heby" },
    { value: "0360", label: "Tierp" },
    { value: "0380", label: "Uppsala" },
    { value: "0381", label: "Enköping" },
    { value: "0382", label: "Östhammar" },
    { value: "0428", label: "Vingåker" },
    { value: "0461", label: "Gnesta" },
    { value: "0480", label: "Nyköping" },
    { value: "0481", label: "Oxelösund" },
    { value: "0482", label: "Flen" },
    { value: "0483", label: "Katrineholm" },
    { value: "0484", label: "Eskilstuna" },
    { value: "0486", label: "Strängnäs" },
    { value: "0488", label: "Trosa" },
    { value: "0509", label: "Ödeshög" },
    { value: "0512", label: "Ydre" },
    { value: "0513", label: "Kinda" },
    { value: "0560", label: "Boxholm" },
    { value: "0561", label: "Åtvidaberg" },
    { value: "0562", label: "Finspång" },
    { value: "0563", label: "Valdemarsvik" },
    { value: "0580", label: "Linköping" },
    { value: "0581", label: "Norrköping" },
    { value: "0582", label: "Söderköping" },
    { value: "0583", label: "Motala" },
    { value: "0584", label: "Vadstena" },
    { value: "0586", label: "Mjölby" },
    { value: "0604", label: "Aneby" },
    { value: "0617", label: "Gnosjö" },
    { value: "0642", label: "Mullsjö" },
    { value: "0643", label: "Habo" },
    { value: "0662", label: "Gislaved" },
    { value: "0665", label: "Vaggeryd" },
    { value: "0680", label: "Jönköping" },
    { value: "0682", label: "Nässjö" },
    { value: "0683", label: "Värnamo" },
    { value: "0684", label: "Sävsjö" },
    { value: "0685", label: "Vetlanda" },
    { value: "0686", label: "Eksjö" },
    { value: "0687", label: "Tranås" },
    { value: "0760", label: "Uppvidinge" },
    { value: "0761", label: "Lessebo" },
    { value: "0763", label: "Tingsryd" },
    { value: "0764", label: "Alvesta" },
    { value: "0765", label: "Älmhult" },
    { value: "0767", label: "Markaryd" },
    { value: "0780", label: "Växjö" },
    { value: "0781", label: "Ljungby" },
    { value: "0821", label: "Högsby" },
    { value: "0834", label: "Torsås" },
    { value: "0840", label: "Mörbylånga" },
    { value: "0860", label: "Hultsfred" },
    { value: "0861", label: "Mönsterås" },
    { value: "0862", label: "Emmaboda" },
    { value: "0880", label: "Kalmar" },
    { value: "0881", label: "Nybro" },
    { value: "0882", label: "Oskarshamn" },
    { value: "0883", label: "Västervik" },
    { value: "0884", label: "Vimmerby" },
    { value: "0885", label: "Borgholm" },
    { value: "0980", label: "Gotland" },
    { value: "1060", label: "Olofström" },
    { value: "1080", label: "Karlskrona" },
    { value: "1081", label: "Ronneby" },
    { value: "1082", label: "Karlshamn" },
    { value: "1083", label: "Sölvesborg" },
    { value: "1214", label: "Svalöv" },
    { value: "1230", label: "Staffanstorp" },
    { value: "1231", label: "Burlöv" },
    { value: "1233", label: "Vellinge" },
    { value: "1256", label: "Östra Göinge" },
    { value: "1257", label: "Örkelljunga" },
    { value: "1260", label: "Bjuv" },
    { value: "1261", label: "Kävlinge" },
    { value: "1262", label: "Lomma" },
    { value: "1263", label: "Svedala" },
    { value: "1264", label: "Skurup" },
    { value: "1265", label: "Sjöbo" },
    { value: "1266", label: "Hörby" },
    { value: "1267", label: "Höör" },
    { value: "1270", label: "Tomelilla" },
    { value: "1272", label: "Bromölla" },
    { value: "1273", label: "Osby" },
    { value: "1275", label: "Perstorp" },
    { value: "1276", label: "Klippan" },
    { value: "1277", label: "Åstorp" },
    { value: "1278", label: "Båstad" },
    { value: "1280", label: "Malmö" },
    { value: "1281", label: "Lund" },
    { value: "1282", label: "Landskrona" },
    { value: "1283", label: "Helsingborg" },
    { value: "1284", label: "Höganäs" },
    { value: "1285", label: "Eslöv" },
    { value: "1286", label: "Ystad" },
    { value: "1287", label: "Trelleborg" },
    { value: "1290", label: "Kristianstad" },
    { value: "1291", label: "Simrishamn" },
    { value: "1292", label: "Ängelholm" },
    { value: "1293", label: "Hässleholm" },
    { value: "1315", label: "Hylte" },
    { value: "1380", label: "Halmstad" },
    { value: "1381", label: "Laholm" },
    { value: "1382", label: "Falkenberg" },
    { value: "1383", label: "Varberg" },
    { value: "1384", label: "Kungsbacka" },
    { value: "1401", label: "Härryda" },
    { value: "1402", label: "Partille" },
    { value: "1407", label: "Öckerö" },
    { value: "1415", label: "Stenungsund" },
    { value: "1419", label: "Tjörn" },
    { value: "1421", label: "Orust" },
    { value: "1427", label: "Sotenäs" },
    { value: "1430", label: "Munkedal" },
    { value: "1435", label: "Tanum" },
    { value: "1438", label: "Dals-Ed" },
    { value: "1439", label: "Färgelanda" },
    { value: "1440", label: "Ale" },
    { value: "1441", label: "Lerum" },
    { value: "1442", label: "Vårgårda" },
    { value: "1443", label: "Bollebygd" },
    { value: "1444", label: "Grästorp" },
    { value: "1445", label: "Essunga" },
    { value: "1446", label: "Karlsborg" },
    { value: "1447", label: "Gullspång" },
    { value: "1452", label: "Tranemo" },
    { value: "1460", label: "Bengtsfors" },
    { value: "1461", label: "Mellerud" },
    { value: "1462", label: "Lilla Edet" },
    { value: "1463", label: "Mark" },
    { value: "1465", label: "Svenljunga" },
    { value: "1466", label: "Herrljunga" },
    { value: "1470", label: "Vara" },
    { value: "1471", label: "Götene" },
    { value: "1472", label: "Tibro" },
    { value: "1473", label: "Töreboda" },
    { value: "1480", label: "Göteborg" },
    { value: "1481", label: "Mölndal" },
    { value: "1482", label: "Kungälv" },
    { value: "1484", label: "Lysekil" },
    { value: "1485", label: "Uddevalla" },
    { value: "1486", label: "Strömstad" },
    { value: "1487", label: "Vänersborg" },
    { value: "1488", label: "Trollhättan" },
    { value: "1489", label: "Alingsås" },
    { value: "1490", label: "Borås" },
    { value: "1491", label: "Ulricehamn" },
    { value: "1492", label: "Åmål" },
    { value: "1493", label: "Mariestad" },
    { value: "1494", label: "Lidköping" },
    { value: "1495", label: "Skara" },
    { value: "1496", label: "Skövde" },
    { value: "1497", label: "Hjo" },
    { value: "1498", label: "Tidaholm" },
    { value: "1499", label: "Falköping" },
    { value: "1715", label: "Kil" },
    { value: "1730", label: "Eda" },
    { value: "1737", label: "Torsby" },
    { value: "1760", label: "Storfors" },
    { value: "1761", label: "Hammarö" },
    { value: "1762", label: "Munkfors" },
    { value: "1763", label: "Forshaga" },
    { value: "1764", label: "Grums" },
    { value: "1765", label: "Årjäng" },
    { value: "1766", label: "Sunne" },
    { value: "1780", label: "Karlstad" },
    { value: "1781", label: "Kristinehamn" },
    { value: "1782", label: "Filipstad" },
    { value: "1783", label: "Hagfors" },
    { value: "1784", label: "Arvika" },
    { value: "1785", label: "Säffle" },
    { value: "1814", label: "Lekeberg" },
    { value: "1860", label: "Laxå" },
    { value: "1861", label: "Hallsberg" },
    { value: "1862", label: "Degerfors" },
    { value: "1863", label: "Hällefors" },
    { value: "1864", label: "Ljusnarsberg" },
    { value: "1880", label: "Örebro" },
    { value: "1881", label: "Kumla" },
    { value: "1882", label: "Askersund" },
    { value: "1883", label: "Karlskoga" },
    { value: "1884", label: "Nora" },
    { value: "1885", label: "Lindesberg" },
    { value: "1904", label: "Skinnskatteberg" },
    { value: "1907", label: "Surahammar" },
    { value: "1960", label: "Kungsör" },
    { value: "1961", label: "Hallstahammar" },
    { value: "1962", label: "Norberg" },
    { value: "1980", label: "Västerås" },
    { value: "1981", label: "Sala" },
    { value: "1982", label: "Fagersta" },
    { value: "1983", label: "Köping" },
    { value: "1984", label: "Arboga" },
    { value: "2021", label: "Vansbro" },
    { value: "2023", label: "Malung-Sälen" },
    { value: "2026", label: "Gagnef" },
    { value: "2029", label: "Leksand" },
    { value: "2031", label: "Rättvik" },
    { value: "2034", label: "Orsa" },
    { value: "2039", label: "Älvdalen" },
    { value: "2061", label: "Smedjebacken" },
    { value: "2062", label: "Mora" },
    { value: "2080", label: "Falun" },
    { value: "2081", label: "Borlänge" },
    { value: "2082", label: "Säter" },
    { value: "2083", label: "Hedemora" },
    { value: "2084", label: "Avesta" },
    { value: "2085", label: "Ludvika" },
    { value: "2101", label: "Ockelbo" },
    { value: "2104", label: "Hofors" },
    { value: "2121", label: "Ovanåker" },
    { value: "2132", label: "Nordanstig" },
    { value: "2161", label: "Ljusdal" },
    { value: "2180", label: "Gävle" },
    { value: "2181", label: "Sandviken" },
    { value: "2182", label: "Söderhamn" },
    { value: "2183", label: "Bollnäs" },
    { value: "2184", label: "Hudiksvall" },
    { value: "2260", label: "Ånge" },
    { value: "2262", label: "Timrå" },
    { value: "2280", label: "Härnösand" },
    { value: "2281", label: "Sundsvall" },
    { value: "2282", label: "Kramfors" },
    { value: "2283", label: "Sollefteå" },
    { value: "2284", label: "Örnsköldsvik" },
    { value: "2303", label: "Ragunda" },
    { value: "2305", label: "Bräcke" },
    { value: "2309", label: "Krokom" },
    { value: "2313", label: "Strömsund" },
    { value: "2321", label: "Åre" },
    { value: "2326", label: "Berg" },
    { value: "2361", label: "Härjedalen" },
    { value: "2380", label: "Östersund" },
    { value: "2401", label: "Nordmaling" },
    { value: "2403", label: "Bjurholm" },
    { value: "2404", label: "Vindeln" },
    { value: "2409", label: "Robertsfors" },
    { value: "2417", label: "Norsjö" },
    { value: "2418", label: "Malå" },
    { value: "2421", label: "Storuman" },
    { value: "2422", label: "Sorsele" },
    { value: "2425", label: "Dorotea" },
    { value: "2460", label: "Vännäs" },
    { value: "2462", label: "Vilhelmina" },
    { value: "2463", label: "Åsele" },
    { value: "2480", label: "Umeå" },
    { value: "2481", label: "Lycksele" },
    { value: "2482", label: "Skellefteå" },
    { value: "2505", label: "Arvidsjaur" },
    { value: "2506", label: "Arjeplog" },
    { value: "2510", label: "Jokkmokk" },
    { value: "2513", label: "Överkalix" },
    { value: "2514", label: "Kalix" },
    { value: "2518", label: "Övertorneå" },
    { value: "2521", label: "Pajala" },
    { value: "2523", label: "Gällivare" },
    { value: "2560", label: "Älvsbyn" },
    { value: "2580", label: "Luleå" },
    { value: "2581", label: "Piteå" },
    { value: "2582", label: "Boden" },
    { value: "2583", label: "Haparanda" },
    { value: "2584", label: "Kiruna" }
];
